language: python

python:
    - 2.7

sudo: false

env:
    - TOXENV=py27-django14-grp
    - TOXENV=py27-django15
    - TOXENV=py27-django15-grp
    - TOXENV=py27-django16
    - TOXENV=py27-django16-grp
    - TOXENV=py27-django17
    - TOXENV=py27-django17-grp
    - TOXENV=py27-django18
    - TOXENV=py27-django18-grp
    - TOXENV=py34-django15
    - TOXENV=py34-django16
    - TOXENV=py34-django17
    - TOXENV=py34-django18

addons:
  apt:
    packages:
    - libexempi3

install:
    - pip install tox 

script:
    - tox
