language: python

sudo: false

addons:
  apt:
    packages:
    - libexempi3

install:
  - pip install tox 

script:
  - travis_retry travis_retry travis_retry tox -- --failfast

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-dj18 }
    - { python: 2.7, env: TOXENV=py27-dj18-grp }
    - { python: 3.4, env: TOXENV=py34-dj18 }
    - { python: 2.7, env: TOXENV=py27-dj19 }
    - { python: 2.7, env: TOXENV=py27-dj19-grp }
    - { python: 3.4, env: TOXENV=py34-dj19 }
    - { python: 2.7, env: TOXENV=py27-dj110 }
    - { python: 2.7, env: TOXENV=py27-dj110-grp }
    - { python: 3.4, env: TOXENV=py34-dj110 }
    - { python: 2.7, env: TOXENV=py27-dj111 }
    - { python: 2.7, env: TOXENV=py27-dj111-grp }
    - { python: 3.6, env: TOXENV=py36-dj111 }
    - python: 3.6
      env: TOXENV=py36-dj20 DATABASE_URL='postgres://postgres@127.0.0.1/cropduster_test'
  allow_failures:
    - env: TOXENV=py36-dj20 DATABASE_URL='postgres://postgres@127.0.0.1/cropduster_test'

cache: pip

before_script:
  - if [ "${DATABASE_URL%%:*}" == "postgres" ]; then psql -c "DROP DATABASE IF EXISTS ${DATABASE_URL##*/};" -U postgres; fi
  - if [ "${DATABASE_URL%%:*}" == "postgres" ]; then psql -c "create database ${DATABASE_URL##*/};" -U postgres; fi
