language: python

python:
    - 2.7
    - 3.4

env:
    - TOXENV=py27-django14
    - TOXENV=py27-django15
    - TOXENV=py34-django15
    - TOXENV=py27-django16 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py34-django16 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py27-django17 DJANGO_SELENIUM_TESTS=1
    - TOXENV=py34-django17 DJANGO_SELENIUM_TESTS=1

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libexempi3

install:
    - pip install tox 

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    - tox

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false
